module.exports = {
  INVALID_SEARCH_PARAMETERS: 'INVALID_SEARCH_PARAMETERS',
  INVALID_LOOKUP_PARAMETERS: 'INVALID_LOOKUP_PARAMETERS',
  // TODO: use INTERNAL_ERROR
  GENERAL_ERROR: 'Something went wrong unexpectedly'
};
